### PR TITLE
Trim repository input

### PR DESCRIPTION
**Pull request by shaedrich**
to prevent showing the default when input has trailing or leading whitespace as seen in #4

Based on https://codepen.io/leaverou/pen/QxKNwZ

Alternatively, if you want to be more strict, you can add a `!contains(' ')` expression to #8

### CODE REVIEW

**Comment by LeaVerou** [comment]
Hey, thanks for the PR! Why did you need to define a separate function, was `.trim()` not working?

**Comment by shaedrich** [comment]
You tell me :D I've never worked with Mavo.js before so I thought, this was the way to go. So you can just use a native function like that as an expression within an HTML string?

**Comment by LeaVerou** [comment]
> You tell me :D I've never worked with Mavo.js before so I thought, this was the way to go. So you can just use a native function like that as an expression within an HTML string?

Yup! It's just that Mavo doesn't promote that, the assumption being that it would be confusing for novices. But it should totally work, unless these are not strings.

**Comment by shaedrich** [comment]
I made the respective changes. However, it's interesting, that `(url('repo') or 'mavoweb/mavo').trim()` is working, while `url('repo').trim() or 'mavoweb/mavo'` is not ^^

**Comment by LeaVerou** [comment]
> I made the respective changes. 

Thanks!

> However, it's interesting, that `(url('repo') or 'mavoweb/mavo').trim()` is working, while `url('repo').trim() or 'mavoweb/mavo'` is not ^^

That is very interesting. What happens with the latter?

**Review by LeaVerou — APPROVED** [review]

**Comment by shaedrich** [comment]
> > However, it's interesting, that `(url('repo') or 'mavoweb/mavo').trim()` is working, while `url('repo').trim() or 'mavoweb/mavo'` is not ^^
> 
> That is very interesting. What happens with the latter?

The latter gets outputted as is:

grafik

**Comment by LeaVerou** [comment]
That looks like it's treated as invalid. Are there any errors in the console?

**Comment by shaedrich** [comment]
Yep, that's it:
grafik

**Comment by LeaVerou** [comment]
Ah bummer. Would you mind filing a bug on the https://github.com/mavoweb/mavo repo?

**Comment by shaedrich** [comment]
Not at all, sure thing: https://github.com/mavoweb/mavo/issues/966

**Pull request merged**
