### PR TITLE
Swap long-color and short-color CSS variables

### LINKED ISSUE #5: Counterintuitive visualization
The more red entries are in the table, the more green the right-hand pie chart gets and vice versa. I assume, this needs to be swapped, right?

### PR DESCRIPTION
**Pull request by shaedrich**
For more intuitive color coding
Fixes #5

### CODE REVIEW

**Comment by LeaVerou** [comment]
Thank you!

**Comment by shaedrich** [comment]
You're welcome!

**Comment by LeaVerou** [comment]
Hey,

This fixed the pie chart but broke the colors for the actual times, which is way worse:

image

Do you want to send a new PR to fix this, or should I just revert this PR?

**Comment by shaedrich** [comment]
Hey,
You'll get a PR in a minute!

**Comment by LeaVerou** [comment]
Thank you so much for the quick response! 🙏🏼

**Comment by shaedrich** [comment]
No problem, happy to contribute :)

**Comment by shaedrich** [comment]
#10 should fix it

**Pull request merged**
